services:
  app:
    build: .
    command: bun run launch:dev
    volumes:
      - .:/app
      - .env:/app/.env
    ports:
      - 3000:3000
    environment:
      - PGHOST=postgres
  postgres:
    image: postgres:17.2-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./local-development/postgres/.db:/var/lib/postgresql/data
      - ./local-development/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
