/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface UrlShortenerRedirects {
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  destination: string;
  hits: Generated<number>;
  id: string;
  pk: Generated<number>;
  updated_at: Generated<Timestamp>;
}

export interface DB {
  "url_shortener.redirects": UrlShortenerRedirects;
}
